server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    error_page 404 /404.html;

    location /_app/ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }

    gzip on;
    gzip_types text/html text/css application/javascript application/json image/svg+xml;
    gzip_min_length 256;

    location / {
        try_files $uri $uri/ $uri.html =404;
    }
}
