export const componentNav = [
	{ label: 'Accordion', href: '/components/accordion' },
	{ label: 'Avatar', href: '/components/avatar' },
	{ label: 'Breadcrumb', href: '/components/breadcrumb' },
	{ label: 'Carousel', href: '/components/carousel' },
	{ label: 'Checkbox', href: '/components/checkbox' },
	{ label: 'Clipboard', href: '/components/clipboard' },
	{ label: 'Collapsible', href: '/components/collapsible' },
	{ label: 'ComboBox', href: '/components/combobox' },
	{ label: 'DatePicker', href: '/components/date-picker' },
	{ label: 'Dialog', href: '/components/dialog' },
	{ label: 'Drawer', href: '/components/drawer' },
	{ label: 'Editable', href: '/components/editable' },
	{ label: 'Field', href: '/components/field' },
	{ label: 'Fieldset', href: '/components/fieldset' },
	{ label: 'FileUpload', href: '/components/file-upload' },
	{ label: 'HoverCard', href: '/components/hover-card' },
	{ label: 'Marquee', href: '/components/marquee' },
	{ label: 'Menu', href: '/components/menu' },
	{ label: 'Modal', href: '/components/modal' },
	{ label: 'NumberInput', href: '/components/number-input' },
	{ label: 'Pagination', href: '/components/pagination' },
	{ label: 'Password Input', href: '/components/password-input' },
	{ label: 'PinInput', href: '/components/pin-input' },
	{ label: 'Popover', href: '/components/popover' },
	{ label: 'QrCode', href: '/components/qr-code' },
	{ label: 'RadioGroup', href: '/components/radio-group' },
	{ label: 'RatingGroup', href: '/components/rating-group' },
	{ label: 'ScrollArea', href: '/components/scroll-area' },
	{ label: 'Select', href: '/components/select' },
	{ label: 'Slider', href: '/components/slider' },
	{ label: 'Splitter', href: '/components/splitter' },
	{ label: 'Steps', href: '/components/steps' },
	{ label: 'Switch', href: '/components/switch' },
	{ label: 'Tabs', href: '/components/tabs' },
	{ label: 'TagsInput', href: '/components/tags-input' },
	{ label: 'Timer', href: '/components/timer' },
	{ label: 'Toast', href: '/components/toast' },
	{ label: 'Toggle', href: '/components/toggle' },
	{ label: 'Tooltip', href: '/components/tooltip' },
	{ label: 'TreeView', href: '/components/tree-view' }
];

export const blockNav = [{ label: 'Chat Panel', href: '/blocks/chat-panel' }];
